namespace ReunionPhotos.Web.Models;

// One row per person allowed to log in. Maps 1:1 to a record in the
// "FamilyMembers" Airtable table. You manage this table directly in
// Airtable: add a row per person, and put their PIN's hash (generated by
// the tools/HashPin utility) into PinHash. Never put a plain PIN in here.
public class FamilyMember
{
    public string Id { get; set; } = "";

    public string Name { get; set; } = "";

    public string PinHash { get; set; } = "";

    public bool Active { get; set; } = true;
}
